[package]
name = "egor00f/UILib"

description = "small library that implement some UI elements"

version = "0.1.0"

registry = "https://github.com/UpliftGames/wally-index"

# or server
realm = "shared"

license = "MIT"

repository = "https://github.com/Egor00f/UILib"

authors = ["Egor00f <velikiydolbayeb@gmail.com>"]

exclude = ["*"]

include = ["src", "src/**", "wally.toml", "README.md", "init.lua"]

private = false

[dependencies]


[server-dependencies]


[dev-dependencies]
